language: objective-c  #1
osx_image: xcode7.3
cache: cocoapods

before_install:
  - brew install swiftlint
  - gem install xcpretty
  - gem install cocoapods

install:
  - pod install

script:
  - swiftlint
  - set -o pipefail && xcodebuild -workspace TopApps.xcworkspace -scheme TopApps destination 'platform=iOS Simulator,name=iPhone 6s Plus' build test CODE_SIGN_IDENTITY=- | xcpretty -c
