language: objective-c  #1
osx_image: xcode7.3
#ache: cocoapods

before_install:
  - gem install xcpretty
  - gem install cocoapods

install:
  - pod install

script:
  - set -o pipefail && xcodebuild -workspace TopApps.xcworkspace -scheme TopApps -destination 'platform=iOS Simulator,name=iPhone 6s Plus' build test | xcpretty -c
