language: objective-c  #1
osx_image: xcode7.3 #2
xcode_workspace: TopApps.xcworkspace #3
xcode_scheme: TopApps #4
xcode_sdk: iphonesimulator9.3 #5
cache: cocoapods

script:
  - xctool test -workspace TopApps.xcworkspace -scheme TopApps -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

branches:
  only:
    - master
