language: objective-c  #1
osx_image: xcode7.3
cache: cocoapods

before_install:
  - gem install xcpretty
  - gem install cocoapods

install:
  - pod install

script:
  - set -o pipefail && xcodebuild -workspace TopApps.xcworkspace -scheme TopApps destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3' build test | xcpretty -c
